# Journal Article Template in Markdown

This is a journal article template for authoring articles with [Markdown](https://en.wikipedia.org/wiki/Markdown).

Although specifically designed for [Chroma: Journal of the Australasian Music Association](https://computermusic.org.au/journal/), it is free to use for any other purpose and may be modified to suit your needs.

The motivation for this project is to provide a way of authoring articles which can be automatically translated into a 1-column PDF (generated by LaTeX), an HTML file for online display, or a Word `docx` file. The `docx` file should be style-similar enough to the PDF document that it can be used by authors who prefer to use Word/OpenOffice to author their writing.

Additional goals include:

- automatic compilation of the `.tex`/`.html`/`.docx` versions of the template using a GitHub Action.

## Required software

## Credits and Inspirations

Developed by Charles Martin, 2021.

- <https://brainbaking.com/post/2021/02/writing-academic-papers-in-markdown/>
- <https://github.com/pandoc/pandoc-action-example>
